### ISSUE TITLE
Unnecessary element in SDR_False_Color_LUT.py

### ISSUE THREAD

**Issue by ghost** [EaryChow/AgX-False-Color-LUTs-Generator#1]
If `LUT_name = "AgX_False_Color"` is already specified on line 68 and since "AgX_False_Color" does not have any spaces,
is `LUT_safe = LUT_name.replace(" ", "_")` on line 69 really required?

**Comment by EaryChow** [comment]
It's part of the boilerplate that I copied and pasted, just thought I should keep it in here just in case for future edits. It doesn't harm to keep it in there anyways.

**Comment by ghost** [comment]
Got it. I got a bit confused as I didn't see it in the HDR one. Speaking of the HDR one, why was it deleted?

**Comment by EaryChow** [comment]
I wrote it on the commit, the HDR version was a failed attempt. I was trying to form a second image for HDR, therefore needing a separate False Color. But after discussing with Troy, it seems using the same image is a better idea. So I didn't end up using the HDR one.

**Comment by ghost** [comment]
Got it, sorry I'm not used to using GitHub on a mobile browser, so I couldn't see the commits. I'm going to close this issue now.
